### ISSUE TITLE
Not working for system applications

### ISSUE THREAD

**Issue by opa334** [CokePokes/libnotifications#1]
While trying to switch from libbulletin to libnotifications, I noticed that no notification is showing up if the bundle identifier is from a system application. I tried "com.apple.mobilesafari" and "com.apple.AppStore", both do not seem to work. When I switched to "net.whatsapp.WhatsApp" for testing, the notification did show. The code is being ran from SpringBoard.

`[NSClassFromString(@"CPNotification") showAlertWithTitle:@"test"
		 message:@"test"
		 userInfo:@{@"" : @""}
		 badgeCount:1
		 soundName:nil
		 delay:1.00
		 repeats:NO
		 bundleId:@"com.apple.mobilesafari"];`

Tested on 11.3.1 (unc0ver) and 12.1.2 (Chimera).

**Comment by CokePokes** [comment]
Oops! You're right, I forgot to add some info to the readMe. So there's two options for you. You can modify the app's Info.plist within your postinst. Add: ```<key>SBAppUsesLocalNotifications</key>
<true/>``` & remove it when the tweak is uninstalled with postrm. (```uicache --all``` must be ran after) 

Or you can add this code to the app's didFinishLaunching or wherever : 

```
if (@available(iOS 10.0, *)) {
        UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
        UNAuthorizationOptions options = UNAuthorizationOptionAlert + UNAuthorizationOptionSound;
        [center requestAuthorizationWithOptions:options completionHandler:^(BOOL granted, NSError * _Nullable error) {
            if (!granted) {
                NSLog(@"Something went wrong");
            }
        }];
    }
```


I'm going to look further into the framework to see if this can be bypassed. Although that may be a long while.

**Comment by CokePokes** [comment]
I updated the readme with this info. Thanks for reminding me!

**Comment by CokePokes** [comment]
@opa334 I'm reopening so you can respond if you still have issues.

**Comment by opa334** [comment]
Even after adding `<key>SBAppUsesLocalNotifications</key> <true/>` to Info.plist and putting the code into applicationDidFinishLaunching, notifications still aren't showing up. requestAuthorizationWithOptions just fails and logs "Something went wrong".

I modified the NSLog to log the NSError too and it said `Notifications are not allowed for this application`.

I believe the reasoning behind this is that Safari is missing the entitlement for push notifications and if I add that, it will break Safari in non jailbroken mode and also there wouldn't really be any use for this library as I could just use the UserNotifications framework directly.

**Comment by opa334** [comment]
Okay, nevermind. Not sure what was wrong but with SBAppUsesLocalNotifications, notifications do indeed show up. The code based solution definitely does not work however. I'm not yet sure whether I want to use this solution. Might reverse UserNotifications a little and see if there's any trivial way to bypass this, as I generally want to avoid modifying the Info.plist if possible.

**Comment by CokePokes** [comment]
@opa334 Yea. I don't like the SBAppUsesLocalNotifications edit either. I'm looking right now how to bypass the authorization but I can't seem to find the class that controls that in Springboard. Although I'm pretty sure thats where it's controlled since I'm seeing: ```SpringBoard(com.apple.UserNotifications.Connections)[8486] <Notice>: [com.apple.mobilesafari] Requesting authorization with options 7```

Let me know if you have any success & i'll add it to this lib.

**Comment by opa334** [comment]
```
- (id)objectsForInfoDictionaryKeys:(id)arg1;
- (id)objectForInfoDictionaryKey:(id)arg1 ofClass:(Class)arg2 valuesOfClass:(Class)arg3;
```

in LSBundleProxy seem to be lowest level api to access the SBAppUsesLocalNotifications key.

I tried hooking the first one to spoof that the key exists inside SpringBoard but it does not seem to actually affect anything. Maybe these have to be hooked inside the libnotificationd process?

**Comment by CokePokes** [comment]
The only issue i have with using that key is that it only works for apps in `/Applications`. It's not a solution for all apps. I've tracked down where authorization takes place. I think. Take a look at [UserNotificationsServer.framework](http://developer.limneos.net/?ios=12.1&framework=UserNotificationsServer.framework&header=UNSDefaultDataProviderFactory.h) There's a ```NSMutableSet* _authorizedBundleIdentifiers;```

**Comment by opa334** [comment]
Success!

```
@interface LSBundleProxy : NSObject
@property (nonatomic,readonly) NSString* bundleIdentifier;
@end

%hook LSBundleProxy

- (id)objectsForInfoDictionaryKeys:(NSArray*)keys
{
	id orig = %orig;

	if([self.bundleIdentifier isEqualToString:@"com.apple.mobilesafari"])
	{
		if([keys containsObject:@"SBAppUsesLocalNotifications"])
		{
			NSMutableDictionary* valuesM = [MSHookIvar<NSDictionary*>(orig, "_values") mutableCopy];

			NSLog(@"s1");

			[valuesM setObject:@1 forKey:@"SBAppUsesLocalNotifications"];

			MSHookIvar<NSDictionary*>(orig, "_values") = [valuesM copy];
		}
	}

	return orig;
}

- (id)objectForInfoDictionaryKey:(NSString*)key ofClass:(Class)arg2 valuesOfClass:(Class)arg3
{
	if([self.bundleIdentifier isEqualToString:@"com.apple.mobilesafari"])
	{
		if([key isEqualToString:@"SBAppUsesLocalNotifications"])
		{
			NSLog(@"s2");
			return @1;
		}
	}

	return %orig;
}

%end
```

This hook needs to be inside SpringBoard and then notifications will show! I don't know if it's a good idea to enable this for every application. Maybe there is a similar way to spoof that the app is a system application, which would then fix this for app store applications.

I found this by reversing SpringBoard's [SBApplicationInfo](http://developer.limneos.net/?ios=11.1.2&framework=SpringBoard&header=SBApplicationInfo.h) class. It has a BOOL systemAppSupportsLocalNotifications, I reversed the - (void)_loadFromProxy:(id)arg1; method to check where this bool comes from. As I said, it also has a systemApplication / internalApplication / appleApplication properties that might be worth looking into. Just hooking SBApplicationInfo is not enough however, the check happens elsewhere.

**Comment by CokePokes** [comment]
Ah nice find. Although, I'm looking for more of a runtime solution. What baffles me is why ```requestAuthorizationWithOptions:``` doesn't automatically show an alert to allow notifications. When that method fails, I should be able to use runtime to show the alert myself. There is the class ```UNSAuthorizationAlertController``` That should allow me to create the alert myself but I can't seem to get it working correctly.  You're better off hooking that class in your tweak, I don't think it would be logical to have that in this lib.

**Comment by opa334** [comment]
Well, guess this is solved. Apparently I don't even need to use this library. I hooked some more methods to pretend that Safari has the aps-environment entitlement and now I can just use the native UserNotifications API.

```
%hook LSBundleProxy

- (NSDictionary*)entitlementValuesForKeys:(NSArray*)keys
{
	NSDictionary* orig = %orig;

	if([self.bundleIdentifier isEqualToString:@"com.apple.mobilesafari"])
	{
		if([keys containsObject:@"aps-environment"])
		{
			NSMutableDictionary* valuesM = [MSHookIvar<NSDictionary*>(orig, "_values") mutableCopy];

			[valuesM setObject:@"production" forKey:@"aps-environment"];

			MSHookIvar<NSDictionary*>(orig, "_values") = [valuesM copy];
		}
	}

	return orig;
}

- (id)entitlementValueForKey:(NSString*)key ofClass:(Class)arg2 valuesOfClass:(Class)arg3
{
	id orig = %orig;

	if([self.bundleIdentifier isEqualToString:@"com.apple.mobilesafari"])
	{
		if([key isEqualToString:@"aps-environment"])
		{
			return @"production";
		}
	}

	return orig;
}

- (id)objectsForInfoDictionaryKeys:(NSArray*)keys
{
	id orig = %orig;

	if([self.bundleIdentifier isEqualToString:@"com.apple.mobilesafari"])
	{
		if([keys containsObject:@"SBAppUsesLocalNotifications"])
		{
			NSMutableDictionary* valuesM = [MSHookIvar<NSDictionary*>(orig, "_values") mutableCopy];

			[valuesM setObject:@1 forKey:@"SBAppUsesLocalNotifications"];

			MSHookIvar<NSDictionary*>(orig, "_values") = [valuesM copy];
		}
	}

	return orig;
}

- (id)objectForInfoDictionaryKey:(NSString*)key ofClass:(Class)arg2 valuesOfClass:(Class)arg3
{
	if([self.bundleIdentifier isEqualToString:@"com.apple.mobilesafari"])
	{
		if([key isEqualToString:@"SBAppUsesLocalNotifications"])
		{
			return @1;
		}
	}

	return %orig;
}

%end

```
